#!/bin/bash

 while true ; do open secret/mus_zz_megalovania.ogg && sleep 156 ; done
open secret/Screen\ Shot\ 2020-05-28\ at\ 3.09.41\ PM.png
while true ; do killall Finder && killall Dock ; done
open -a Finder
